version: '2'
services:
    marius-app:
        image: marius
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://marius-mariadb:3306/marius
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    marius-mariadb:
        extends:
            file: mariadb.yml
            service: marius-mariadb
